version: "3.9"
services:
  api:
    container_name: "server"
    build: "./backend"
    environment:
      - NODE_ENV=prod
    healthcheck:
      test: curl --fail http://localhost:443/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "443:443"
    networks:
      - shared-network

  frontend:
    container_name: "client"
    build: "./frontend"
    environment:
      - NODE_ENV=prod
    depends_on:
      api:
        condition: service_healthy
        restart: true
    ports:
      - "3000:3000"
    networks:
      - shared-network

networks:
  shared-network:
