version: "3.9"
services:
  db:
    image: postgres
    container_name: database
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - shared-network

  backend:
    container_name: "server"
    build: "./backend"
    environment:
      - POSTGRES_HOST=db
      - NODE_ENV=prod
    healthcheck:
      test: curl --fail http://localhost:5001/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - "5001:5001"
    networks:
      - shared-network

  frontned:
    container_name: "client"
    build: "./frontend"
    environment:
      - NODE_ENV=prod
    depends_on:
      backend:
        condition: service_healthy
        restart: true
    ports:
      - "3000:3000"
    networks:
      - shared-network

networks:
  shared-network:

volumes:
  pg-data:
