version: "3.9"
services:
  db:
    image: postgres
    container_name: database
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data

volumes:
  dev-db-data:
